# Generated by Django 4.1.5 on 2023-01-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
