# Generated by Django 4.1.5 on 2023-01-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_embeded',
            field=models.URLField(default='', verbose_name='https://www.youtube.com/embed<django.db.model'),
            preserve_default=False,
        ),
    ]
