# Generated by Django 4.1.5 on 2023-01-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_youtube_embeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_embeded',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
